/**
 * Initial Page-by-Page SEO Dataset for ONPRINT Dubai
 * Every indexable URL has its own unique title, description, focus keyword, H1,
 * canonical, Open Graph metadata, Twitter metadata, schema markup, and SEO score.
 * Strictly NO duplicate SEO and NO dummy/placeholder data.
 */

const SITE_URL = (process.env.SITE_URL || 'https://0nprint.com').replace(/\/$/, '')

const initialPageSeoRecords = [
  // ==========================================
  // 1. PRIMARY STATIC PAGES
  // ==========================================
  {
    page_type: 'homepage',
    page_id: null,
    url: '/',
    slug: 'home',
    meta_title: 'ONPRINT | Professional Printing Services in Dubai',
    meta_description: 'Premier commercial printing press in Dubai. Precision offset & digital printing, corporate stationery, luxury packaging, promotional gifts, and fast UAE delivery.',
    focus_keyword: 'printing services dubai',
    secondary_keywords: 'commercial printing dubai, digital printing press dubai, offset printing dubai, corporate printing uae',
    h1: 'Professional Printing & Branding Solutions in Dubai',
    seo_content: 'ONPRINT is Dubai’s trusted commercial printing partner, providing offset, digital, and large-format printing for corporations, agencies, and luxury brands across the UAE.',
    canonical_url: `${SITE_URL}/`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'ONPRINT | Professional Commercial Printing in Dubai',
    og_description: 'Dubai premier printing company. Precision digital & offset printing, corporate gifts, business cards, stationery, packaging, and large-format signage.',
    og_image: `${SITE_URL}/logo_icon.png`,
    twitter_title: 'ONPRINT | Professional Printing Services in Dubai',
    twitter_description: 'High precision offset & digital printing across Dubai and the UAE.',
    twitter_image: `${SITE_URL}/logo_icon.png`,
    schema_type: 'Organization',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@graph': [
        {
          '@type': 'LocalBusiness',
          '@id': `${SITE_URL}/#organization`,
          name: 'ONPRINT',
          url: `${SITE_URL}`,
          logo: `${SITE_URL}/logo_icon.png`,
          telephone: '+9714800PRINT',
          email: 'info@onprint.ae',
          priceRange: '$$',
          address: {
            '@type': 'PostalAddress',
            streetAddress: 'Al Quoz Industrial Area 3',
            addressLocality: 'Dubai',
            addressRegion: 'Dubai',
            postalCode: '00000',
            addressCountry: 'AE',
          },
          geo: { '@type': 'GeoCoordinates', latitude: 25.1328, longitude: 55.2348 },
          areaServed: ['Dubai', 'Abu Dhabi', 'Sharjah', 'United Arab Emirates'],
        },
        {
          '@type': 'WebSite',
          '@id': `${SITE_URL}/#website`,
          url: `${SITE_URL}`,
          name: 'ONPRINT Printing Dubai',
          potentialAction: {
            '@type': 'SearchAction',
            target: `${SITE_URL}/products?q={search_term_string}`,
            'query-input': 'required name=search_term_string',
          },
        },
      ],
    }),
    seo_score: 96,
    readability_score: 82,
  },
  {
    page_type: 'about',
    page_id: null,
    url: '/about',
    slug: 'about',
    meta_title: 'About ONPRINT | Leading Printing Press in Al Quoz, Dubai',
    meta_description: 'Discover ONPRINT, Dubai’s dedicated corporate printing and branding facility in Al Quoz. Over a decade of press craftsmanship delivering flawless commercial print across the UAE.',
    focus_keyword: 'about onprint',
    secondary_keywords: 'printing press dubai, al quoz printing company, commercial printer uae, onprint profile',
    h1: 'Decades of Precision Print Engineering in Dubai',
    seo_content: 'Located in Al Quoz, ONPRINT combines traditional Heidelberg offset craftsmanship with state-of-the-art HP Indigo digital presses to deliver luxury printing for UAE enterprises.',
    canonical_url: `${SITE_URL}/about`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'About ONPRINT | Leading Printing Press in Al Quoz, Dubai',
    og_description: 'Decades of collective press experience delivering flawless print collateral across Dubai and the UAE.',
    og_image: `${SITE_URL}/logo_icon.png`,
    twitter_title: 'About ONPRINT | Leading Printing Press in Al Quoz, Dubai',
    twitter_description: 'Decades of collective press experience delivering flawless print collateral across Dubai and the UAE.',
    twitter_image: `${SITE_URL}/logo_icon.png`,
    schema_type: 'AboutPage',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'AboutPage',
      name: 'About ONPRINT Dubai',
      url: `${SITE_URL}/about`,
      description: 'Corporate overview and printing press capabilities of ONPRINT Dubai in Al Quoz.',
      publisher: { '@id': `${SITE_URL}/#organization` },
    }),
    seo_score: 94,
    readability_score: 85,
  },
  {
    page_type: 'contact',
    page_id: null,
    url: '/contact',
    slug: 'contact',
    meta_title: 'Contact ONPRINT Dubai | Corporate Printing Press Al Quoz',
    meta_description: 'Get in touch with ONPRINT Dubai. Located in Al Quoz Industrial Area. Reach our commercial print estimators, schedule press checks, or request bespoke corporate consultations.',
    focus_keyword: 'contact onprint dubai',
    secondary_keywords: 'printing company contact dubai, print press location al quoz, print estimator uae',
    h1: 'Connect with Dubai Commercial Printing Specialists',
    seo_content: 'Direct contact portal for ONPRINT Dubai. Our print estimating and production team is available for bespoke quotation reviews, paper stock consultations, and press checks.',
    canonical_url: `${SITE_URL}/contact`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Contact ONPRINT Dubai | Commercial Printing Press Al Quoz',
    og_description: 'Connect directly with our print estimators and production studio in Al Quoz Industrial Area 3, Dubai.',
    og_image: `${SITE_URL}/logo_icon.png`,
    twitter_title: 'Contact ONPRINT Dubai | Commercial Printing Press Al Quoz',
    twitter_description: 'Connect directly with our print estimators and production studio in Al Quoz Industrial Area 3, Dubai.',
    twitter_image: `${SITE_URL}/logo_icon.png`,
    schema_type: 'ContactPage',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'ContactPage',
      name: 'Contact ONPRINT Dubai',
      url: `${SITE_URL}/contact`,
      telephone: '+9714800PRINT',
      email: 'info@onprint.ae',
      address: {
        '@type': 'PostalAddress',
        streetAddress: 'Al Quoz Industrial Area 3',
        addressLocality: 'Dubai',
        addressCountry: 'AE',
      },
    }),
    seo_score: 92,
    readability_score: 88,
  },
  {
    page_type: 'services',
    page_id: null,
    url: '/services',
    slug: 'services',
    meta_title: 'Printing Services in Dubai | ONPRINT',
    meta_description: 'Explore commercial printing services in Dubai. High-speed digital printing, volume offset runs, luxury foil stamping, custom packaging, and large-format rollups across the UAE.',
    focus_keyword: 'commercial printing services dubai',
    secondary_keywords: 'offset printing dubai, digital printing services uae, custom packaging printing dubai, corporate print solutions',
    h1: 'Commercial & Corporate Printing Services in Dubai',
    seo_content: 'Comprehensive print service catalog covering digital quick prints, corporate stationery suites, event branding, marketing brochures, and high-volume offset manufacturing.',
    canonical_url: `${SITE_URL}/services`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Printing Services in Dubai | ONPRINT',
    og_description: 'Explore our full commercial printing capabilities in Dubai with fast turnaround and calibrated Pantone precision.',
    og_image: `${SITE_URL}/logo_icon.png`,
    twitter_title: 'Printing Services in Dubai | ONPRINT',
    twitter_description: 'Explore our full commercial printing capabilities in Dubai with fast turnaround and calibrated Pantone precision.',
    twitter_image: `${SITE_URL}/logo_icon.png`,
    schema_type: 'CollectionPage',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'CollectionPage',
      name: 'Commercial Printing Services Dubai',
      url: `${SITE_URL}/services`,
      description: 'Comprehensive directory of corporate and commercial printing services in Dubai.',
    }),
    seo_score: 95,
    readability_score: 80,
  },
  {
    page_type: 'categories',
    page_id: null,
    url: '/categories',
    slug: 'categories',
    meta_title: 'Commercial Printing Categories in Dubai | ONPRINT',
    meta_description: 'Browse all commercial printing categories by ONPRINT Dubai. From luxury business cards and marketing brochures to corporate lanyards and ID badges.',
    focus_keyword: 'printing categories dubai',
    secondary_keywords: 'print product catalog dubai, corporate stationery categories, marketing collateral uae',
    h1: 'Corporate Printing Disciplines & Categories',
    seo_content: 'Explore ONPRINT printing categories covering executive visiting cards, corporate brochures, promotional flyers, employee identity badges, and official stationery.',
    canonical_url: `${SITE_URL}/categories`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Commercial Printing Categories in Dubai | ONPRINT',
    og_description: 'Browse all corporate printing product categories manufactured by ONPRINT in Dubai, UAE.',
    og_image: `${SITE_URL}/logo_icon.png`,
    twitter_title: 'Commercial Printing Categories in Dubai | ONPRINT',
    twitter_description: 'Browse all corporate printing product categories manufactured by ONPRINT in Dubai, UAE.',
    twitter_image: `${SITE_URL}/logo_icon.png`,
    schema_type: 'CollectionPage',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'CollectionPage',
      name: 'Commercial Printing Categories Dubai',
      url: `${SITE_URL}/categories`,
    }),
    seo_score: 93,
    readability_score: 84,
  },
  {
    page_type: 'products',
    page_id: null,
    url: '/products',
    slug: 'products',
    meta_title: 'Custom Printing Products Dubai | Corporate Merchandise | ONPRINT',
    meta_description: 'Order custom commercial print products in Dubai. Business cards, multi-page brochures, promotional flyers, smart ID cards, branded lanyards, and official letterheads.',
    focus_keyword: 'custom printing products dubai',
    secondary_keywords: 'print supplies dubai, promotional merchandise uae, branded corporate gifts dubai',
    h1: 'Custom Printing Products & Corporate Supplies Dubai',
    seo_content: 'Order luxury print products online in Dubai. High-end paper stocks, soft-touch velvet laminates, hot metallic foil finishes, and express same-day dispatch.',
    canonical_url: `${SITE_URL}/products`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Custom Printing Products Dubai | Corporate Merchandise | ONPRINT',
    og_description: 'Order custom printed corporate products in Dubai with live instant pricing and volume wholesale rates.',
    og_image: `${SITE_URL}/logo_icon.png`,
    twitter_title: 'Custom Printing Products Dubai | Corporate Merchandise | ONPRINT',
    twitter_description: 'Order custom printed corporate products in Dubai with live instant pricing and volume wholesale rates.',
    twitter_image: `${SITE_URL}/logo_icon.png`,
    schema_type: 'CollectionPage',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'CollectionPage',
      name: 'Custom Printing Products Dubai',
      url: `${SITE_URL}/products`,
    }),
    seo_score: 95,
    readability_score: 81,
  },
  {
    page_type: 'blog',
    page_id: null,
    url: '/blog',
    slug: 'blog',
    meta_title: 'Printing Industry Insights & Guides | ONPRINT',
    meta_description: 'Authoritative commercial printing guides, paper stock comparisons, finishing techniques, and corporate branding strategies from ONPRINT Dubai press specialists.',
    focus_keyword: 'printing blog dubai',
    secondary_keywords: 'printing guides uae, paper stock guide dubai, corporate branding tips, commercial print news',
    h1: 'Printing Insights, Technical Guides & Press News',
    seo_content: 'In-depth industry analysis, technical prepress tips, paper gsm guides, and executive print finishing comparisons compiled by ONPRINT senior press engineers in Dubai.',
    canonical_url: `${SITE_URL}/blog`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Printing Industry Insights & Guides | ONPRINT',
    og_description: 'Technical guides, finishing comparisons, and executive print advice for UAE businesses.',
    og_image: `${SITE_URL}/logo_icon.png`,
    twitter_title: 'Printing Industry Insights & Guides | ONPRINT',
    twitter_description: 'Technical guides, finishing comparisons, and executive print advice for UAE businesses.',
    twitter_image: `${SITE_URL}/logo_icon.png`,
    schema_type: 'Blog',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'Blog',
      name: 'ONPRINT Printing Insights Dubai',
      url: `${SITE_URL}/blog`,
    }),
    seo_score: 94,
    readability_score: 86,
  },
  {
    page_type: 'portfolio',
    page_id: null,
    url: '/portfolio',
    slug: 'portfolio',
    meta_title: 'Commercial Print & Luxury Branding Portfolio Dubai | ONPRINT',
    meta_description: 'Inspect our curated showcase of executive corporate stationery, luxury packaging boxes, and high-impact press projects produced for premier UAE brands.',
    focus_keyword: 'printing portfolio dubai',
    secondary_keywords: 'print samples dubai, luxury packaging showcase uae, corporate branding portfolio',
    h1: 'Commercial Printing & Luxury Branding Showcase',
    seo_content: 'Browse actual photographs and finish specifications of completed print runs for Dubai luxury hotels, corporate finance firms, and retail brands.',
    canonical_url: `${SITE_URL}/portfolio`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Commercial Print & Luxury Branding Portfolio Dubai | ONPRINT',
    og_description: 'Curated editorial showcase of luxury stationery, packaging, and high-impact press projects in Dubai.',
    og_image: `${SITE_URL}/logo_icon.png`,
    twitter_title: 'Commercial Print & Luxury Branding Portfolio Dubai | ONPRINT',
    twitter_description: 'Curated editorial showcase of luxury stationery, packaging, and high-impact press projects in Dubai.',
    twitter_image: `${SITE_URL}/logo_icon.png`,
    schema_type: 'CollectionPage',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'CollectionPage',
      name: 'Commercial Printing Portfolio Dubai',
      url: `${SITE_URL}/portfolio`,
    }),
    seo_score: 93,
    readability_score: 83,
  },
  {
    page_type: 'quote',
    page_id: null,
    url: '/get-a-quote',
    slug: 'get-a-quote',
    meta_title: 'Request Instant Printing Quote Dubai | ONPRINT',
    meta_description: 'Request a custom commercial printing estimate in Dubai. Fast transparent turnaround, volume wholesale pricing, paper stock consultation, and express UAE delivery.',
    focus_keyword: 'printing quote dubai',
    secondary_keywords: 'print price estimate dubai, instant print quotation uae, commercial print pricing',
    h1: 'Request Your Custom Dubai Commercial Print Quotation',
    seo_content: 'Submit project specifications, dimensions, quantity, paper stock, and custom finishes to receive a verified commercial print quote within hours.',
    canonical_url: `${SITE_URL}/get-a-quote`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Request Instant Printing Quote Dubai | ONPRINT',
    og_description: 'Get transparent wholesale and corporate pricing for commercial print projects in Dubai.',
    og_image: `${SITE_URL}/logo_icon.png`,
    twitter_title: 'Request Instant Printing Quote Dubai | ONPRINT',
    twitter_description: 'Get transparent wholesale and corporate pricing for commercial print projects in Dubai.',
    twitter_image: `${SITE_URL}/logo_icon.png`,
    schema_type: 'WebPage',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: 'Request Print Quote Dubai',
      url: `${SITE_URL}/get-a-quote`,
    }),
    seo_score: 92,
    readability_score: 85,
  },
  {
    page_type: 'faq',
    page_id: null,
    url: '/faq',
    slug: 'faq',
    meta_title: 'Frequently Asked Questions | ONPRINT Dubai Printing Press',
    meta_description: 'Find answers regarding print turnaround times, minimum order quantities, paper stocks, artwork preflight requirements, and delivery across Dubai and the UAE.',
    focus_keyword: 'dubai printing faq',
    secondary_keywords: 'printing questions dubai, print turnaround uae, artwork guidelines dubai',
    h1: 'Commercial Printing Press FAQs & Production Guidelines',
    seo_content: 'Comprehensive answers to common questions about artwork bleeds, color calibration, paper weights, lamination types, payment terms, and delivery across UAE.',
    canonical_url: `${SITE_URL}/faq`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Frequently Asked Questions | ONPRINT Dubai Printing Press',
    og_description: 'Production guidelines, turnaround schedules, and technical prepress FAQs.',
    og_image: `${SITE_URL}/logo_icon.png`,
    twitter_title: 'Frequently Asked Questions | ONPRINT Dubai Printing Press',
    twitter_description: 'Production guidelines, turnaround schedules, and technical prepress FAQs.',
    twitter_image: `${SITE_URL}/logo_icon.png`,
    schema_type: 'FAQPage',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: [
        {
          '@type': 'Question',
          name: 'What is the standard turnaround time for printing in Dubai?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'Standard production takes 2 to 4 business days. Express same-day digital printing is available on selected items.',
          },
        },
        {
          '@type': 'Question',
          name: 'Do you provide delivery across all UAE emirates?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'Yes, ONPRINT provides courier delivery across Dubai, Abu Dhabi, Sharjah, Ajman, RAK, Fujairah, and UAQ.',
          },
        },
      ],
    }),
    seo_score: 94,
    readability_score: 88,
  },
  {
    page_type: 'static',
    page_id: null,
    url: '/track-order',
    slug: 'track-order',
    meta_title: 'Track Print Production & Order Status | ONPRINT Dubai',
    meta_description: 'Track the real-time production, quality inspection, and dispatch status of your commercial print orders with ONPRINT Dubai.',
    focus_keyword: 'track print order dubai',
    secondary_keywords: 'onprint order tracking, print status uae, delivery tracking dubai',
    h1: 'Real-Time Print Order Production & Dispatch Tracker',
    seo_content: 'Enter your ONPRINT order number to monitor live prepress verification, press scheduling, post-press finishing, and courier dispatch stages.',
    canonical_url: `${SITE_URL}/track-order`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Track Print Production & Order Status | ONPRINT Dubai',
    og_description: 'Real-time production tracker for corporate printing orders in Dubai.',
    og_image: `${SITE_URL}/logo_icon.png`,
    twitter_title: 'Track Print Production & Order Status | ONPRINT Dubai',
    twitter_description: 'Real-time production tracker for corporate printing orders in Dubai.',
    twitter_image: `${SITE_URL}/logo_icon.png`,
    schema_type: 'WebPage',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: 'Track Print Order ONPRINT Dubai',
      url: `${SITE_URL}/track-order`,
    }),
    seo_score: 90,
    readability_score: 89,
  },
  {
    page_type: 'static',
    page_id: null,
    url: '/privacy-policy',
    slug: 'privacy-policy',
    meta_title: 'Privacy Policy | ONPRINT Commercial Printing Dubai',
    meta_description: 'Read the ONPRINT privacy policy. How we safeguard corporate artwork files, customer data, and payment information in Dubai, UAE.',
    focus_keyword: 'onprint privacy policy',
    secondary_keywords: 'privacy policy printing company dubai, data security uae',
    h1: 'Corporate Privacy Policy & Data Security',
    seo_content: 'Our commitment to protecting corporate intellectual property, artwork vector files, and customer information.',
    canonical_url: `${SITE_URL}/privacy-policy`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Privacy Policy | ONPRINT Commercial Printing Dubai',
    og_description: 'How ONPRINT safeguards customer data and corporate design assets.',
    og_image: `${SITE_URL}/logo_icon.png`,
    twitter_title: 'Privacy Policy | ONPRINT Commercial Printing Dubai',
    twitter_description: 'How ONPRINT safeguards customer data and corporate design assets.',
    twitter_image: `${SITE_URL}/logo_icon.png`,
    schema_type: 'WebPage',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: 'ONPRINT Privacy Policy',
      url: `${SITE_URL}/privacy-policy`,
    }),
    seo_score: 88,
    readability_score: 78,
  },
  {
    page_type: 'static',
    page_id: null,
    url: '/terms',
    slug: 'terms',
    meta_title: 'Terms & Conditions | ONPRINT Commercial Printing Dubai',
    meta_description: 'Review terms and commercial printing conditions for ONPRINT Dubai, covering prepress approvals, color matching standards, and delivery terms.',
    focus_keyword: 'onprint terms conditions',
    secondary_keywords: 'commercial printing terms dubai, print production agreements uae',
    h1: 'Commercial Printing Terms & Service Agreements',
    seo_content: 'Production conditions, customer proof approval obligations, CMYK Pantone tolerances, and delivery terms.',
    canonical_url: `${SITE_URL}/terms`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Terms & Conditions | ONPRINT Commercial Printing Dubai',
    og_description: 'Commercial printing agreements and production standards in Dubai.',
    og_image: `${SITE_URL}/logo_icon.png`,
    twitter_title: 'Terms & Conditions | ONPRINT Commercial Printing Dubai',
    twitter_description: 'Commercial printing agreements and production standards in Dubai.',
    twitter_image: `${SITE_URL}/logo_icon.png`,
    schema_type: 'WebPage',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: 'ONPRINT Terms of Service',
      url: `${SITE_URL}/terms`,
    }),
    seo_score: 88,
    readability_score: 76,
  },

  // ==========================================
  // 2. CATEGORY PAGES (Independent SEO per Category)
  // ==========================================
  {
    page_type: 'category',
    page_id: 1,
    url: '/categories/brochures-printing',
    slug: 'brochures-printing',
    meta_title: 'Brochures Printing in Dubai | Premium Brochure Printing | ONPRINT',
    meta_description: 'Professional brochure printing in Dubai. Custom bi-fold, tri-fold, and multi-page marketing brochures with soft-touch matte lamination and fast turnaround.',
    focus_keyword: 'brochures printing dubai',
    secondary_keywords: 'brochure printing dubai, corporate brochures uae, custom bi fold brochures',
    h1: 'Commercial Brochure Printing in Dubai',
    seo_content: 'Luxury corporate bi-fold, tri-fold, and multi-page brochures printed on 170gsm to 350gsm coated art paper with precision folding and spot UV options.',
    canonical_url: `${SITE_URL}/categories/brochures-printing`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Brochures Printing in Dubai | Luxury Commercial Brochures | ONPRINT',
    og_description: 'Professional corporate brochure printing in Dubai with precision creasing and velvet laminates.',
    og_image: `${SITE_URL}/uploads/categories/brochures-printing.jpg`,
    twitter_title: 'Brochures Printing in Dubai | Premium Brochure Printing | ONPRINT',
    twitter_description: 'Professional corporate brochure printing in Dubai with precision creasing and velvet laminates.',
    twitter_image: `${SITE_URL}/uploads/categories/brochures-printing.jpg`,
    schema_type: 'CollectionPage',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'CollectionPage',
      name: 'Brochures Printing Dubai',
      url: `${SITE_URL}/categories/brochures-printing`,
      description: 'Custom corporate brochure printing in Dubai.',
    }),
    seo_score: 95,
    readability_score: 82,
  },
  {
    page_type: 'category',
    page_id: 2,
    url: '/categories/business-cards-printing',
    slug: 'business-cards-printing',
    meta_title: 'Business Card Printing in Dubai | Luxury Business Cards | ONPRINT',
    meta_description: 'Make an undeniable first impression with luxury business cards in Dubai. 350gsm–600gsm cotton stocks, gold foil stamping, and spot UV varnishing.',
    focus_keyword: 'business cards printing dubai',
    secondary_keywords: 'luxury business cards dubai, executive visiting cards uae, gold foil business cards',
    h1: 'Luxury Executive Business Card Printing in Dubai',
    seo_content: 'Executive 350gsm to 600gsm cotton and silk business cards with soft-touch velvet lamination, metallic hot gold foil stamping, and painted colored edges.',
    canonical_url: `${SITE_URL}/categories/business-cards-printing`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Business Card Printing in Dubai | Luxury Business Cards | ONPRINT',
    og_description: 'Luxury executive business card printing in Dubai with hot foil stamping and painted edges.',
    og_image: `${SITE_URL}/uploads/categories/business-cards-printing.jpg`,
    twitter_title: 'Business Card Printing in Dubai | Luxury Business Cards | ONPRINT',
    twitter_description: 'Luxury executive business card printing in Dubai with hot foil stamping and painted edges.',
    twitter_image: `${SITE_URL}/uploads/categories/business-cards-printing.jpg`,
    schema_type: 'CollectionPage',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'CollectionPage',
      name: 'Business Cards Printing Dubai',
      url: `${SITE_URL}/categories/business-cards-printing`,
    }),
    seo_score: 96,
    readability_score: 85,
  },
  {
    page_type: 'category',
    page_id: 3,
    url: '/categories/flyers-printing-in-dubai',
    slug: 'flyers-printing-in-dubai',
    meta_title: 'Flyer Printing in Dubai | Same Day Marketing Flyer Printing | ONPRINT',
    meta_description: 'Order custom marketing flyer printing in Dubai. Single and double-sided promo flyers on premium art paper with express same-day delivery.',
    focus_keyword: 'flyers printing in dubai',
    secondary_keywords: 'flyer printing dubai, promotional flyers uae, marketing leaflets dubai',
    h1: 'High-Impact Marketing Flyer Printing in Dubai',
    seo_content: 'Vibrant CMYK promotional flyers printed on 170gsm–300gsm gloss or silk art paper with express turnaround for Dubai exhibitions and retail promotions.',
    canonical_url: `${SITE_URL}/categories/flyers-printing-in-dubai`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Flyer Printing in Dubai | Express Marketing Leaflets | ONPRINT',
    og_description: 'High impact single and double sided marketing flyers printed in Dubai.',
    og_image: `${SITE_URL}/uploads/categories/flyers-printing-in-dubai.jpg`,
    twitter_title: 'Flyer Printing in Dubai | Express Marketing Leaflets | ONPRINT',
    twitter_description: 'High impact single and double sided marketing flyers printed in Dubai.',
    twitter_image: `${SITE_URL}/uploads/categories/flyers-printing-in-dubai.jpg`,
    schema_type: 'CollectionPage',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'CollectionPage',
      name: 'Flyers Printing Dubai',
      url: `${SITE_URL}/categories/flyers-printing-in-dubai`,
    }),
    seo_score: 94,
    readability_score: 84,
  },
  {
    page_type: 'category',
    page_id: 4,
    url: '/categories/id-card-printing-dubai',
    slug: 'id-card-printing-dubai',
    meta_title: 'ID Card Printing Dubai | Corporate Employee & PVC Cards | ONPRINT',
    meta_description: 'High-security corporate PVC ID card printing in Dubai. Crisp photo resolution, smart NFC chips, barcodes, and custom lanyards for UAE businesses.',
    focus_keyword: 'id card printing dubai',
    secondary_keywords: 'pvc id cards dubai, corporate employee badges uae, student id card printing',
    h1: 'Corporate PVC ID Card Printing Solutions Dubai',
    seo_content: 'CR80 standard PVC identity cards with high-definition thermal transfer, smart RFID/NFC chips, barcodes, magnetic stripes, and custom security overlays.',
    canonical_url: `${SITE_URL}/categories/id-card-printing-dubai`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'ID Card Printing Dubai | Corporate Employee & PVC Cards | ONPRINT',
    og_description: 'High security PVC employee identity cards printed in Dubai.',
    og_image: `${SITE_URL}/uploads/categories/id-card-printing-dubai.jpg`,
    twitter_title: 'ID Card Printing Dubai | Corporate Employee & PVC Cards | ONPRINT',
    twitter_description: 'High security PVC employee identity cards printed in Dubai.',
    twitter_image: `${SITE_URL}/uploads/categories/id-card-printing-dubai.jpg`,
    schema_type: 'CollectionPage',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'CollectionPage',
      name: 'ID Card Printing Dubai',
      url: `${SITE_URL}/categories/id-card-printing-dubai`,
    }),
    seo_score: 93,
    readability_score: 83,
  },
  {
    page_type: 'category',
    page_id: 5,
    url: '/categories/lanyard-printing-dubai',
    slug: 'lanyard-printing-dubai',
    meta_title: 'Lanyard Printing Dubai | Custom Branded Neck Lanyards | ONPRINT',
    meta_description: 'Custom branded neck lanyard printing in Dubai. High-density polyester and satin lanyards with safety buckles and swivel hooks for corporate events.',
    focus_keyword: 'lanyard printing dubai',
    secondary_keywords: 'custom lanyards dubai, branded neck straps uae, event lanyards dubai',
    h1: 'Custom Branded Neck Lanyard Printing in Dubai',
    seo_content: 'Custom corporate lanyards in satin and woven polyester with screen printing or dye-sublimation, safety breakaway buckles, and heavy-duty metal clips.',
    canonical_url: `${SITE_URL}/categories/lanyard-printing-dubai`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Lanyard Printing Dubai | Custom Branded Neck Lanyards | ONPRINT',
    og_description: 'Custom branded corporate neck lanyards manufactured in Dubai.',
    og_image: `${SITE_URL}/uploads/categories/lanyard-printing-dubai.jpg`,
    twitter_title: 'Lanyard Printing Dubai | Custom Branded Neck Lanyards | ONPRINT',
    twitter_description: 'Custom branded corporate neck lanyards manufactured in Dubai.',
    twitter_image: `${SITE_URL}/uploads/categories/lanyard-printing-dubai.jpg`,
    schema_type: 'CollectionPage',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'CollectionPage',
      name: 'Lanyard Printing Dubai',
      url: `${SITE_URL}/categories/lanyard-printing-dubai`,
    }),
    seo_score: 93,
    readability_score: 85,
  },
  {
    page_type: 'category',
    page_id: 6,
    url: '/categories/letterheads-printing-dubai',
    slug: 'letterheads-printing-dubai',
    meta_title: 'Letterhead Printing in Dubai | Official Corporate Stationery | ONPRINT',
    meta_description: 'Executive corporate letterhead printing in Dubai. 120gsm smooth laser-guaranteed paper for official contracts, proposals, and invoices.',
    focus_keyword: 'letterheads printing dubai',
    secondary_keywords: 'letterhead printing dubai, corporate stationery uae, official letterhead paper',
    h1: 'Executive Corporate Letterhead Printing in Dubai',
    seo_content: '120gsm ultra-smooth uncoated official corporate letterheads with laser-guaranteed printer compatibility and calibrated Pantone spot color fidelity.',
    canonical_url: `${SITE_URL}/categories/letterheads-printing-dubai`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Letterhead Printing in Dubai | Official Corporate Stationery | ONPRINT',
    og_description: 'Executive corporate letterheads printed on 120gsm laser-guaranteed paper.',
    og_image: `${SITE_URL}/uploads/categories/letterheads-printing-dubai.jpg`,
    twitter_title: 'Letterhead Printing in Dubai | Official Corporate Stationery | ONPRINT',
    twitter_description: 'Executive corporate letterheads printed on 120gsm laser-guaranteed paper.',
    twitter_image: `${SITE_URL}/uploads/categories/letterheads-printing-dubai.jpg`,
    schema_type: 'CollectionPage',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'CollectionPage',
      name: 'Letterheads Printing Dubai',
      url: `${SITE_URL}/categories/letterheads-printing-dubai`,
    }),
    seo_score: 92,
    readability_score: 86,
  },
  {
    page_type: 'category',
    page_id: 7,
    url: '/categories/name-badges-printing-dubai',
    slug: 'name-badges-printing-dubai',
    meta_title: 'Name Badges Printing Dubai | Magnetic Metal & Acrylic Badges | ONPRINT',
    meta_description: 'Professional staff name badges printing in Dubai. Brushed silver, gold, and acrylic magnetic badges with domed epoxy resin for corporate teams.',
    focus_keyword: 'name badges printing dubai',
    secondary_keywords: 'magnetic name badges dubai, staff badge printing uae, acrylic name tag printing',
    h1: 'Professional Magnetic Name Badges Printing Dubai',
    seo_content: 'Laser-cut brushed champagne gold, silver, and acrylic employee name badges with crystal-clear domed epoxy coating and strong neodymium magnets.',
    canonical_url: `${SITE_URL}/categories/name-badges-printing-dubai`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Name Badges Printing Dubai | Magnetic Metal & Acrylic Badges | ONPRINT',
    og_description: 'Professional magnetic metal and acrylic name badges printed in Dubai.',
    og_image: `${SITE_URL}/uploads/categories/name-badges-printing-dubai.jpg`,
    twitter_title: 'Name Badges Printing Dubai | Magnetic Metal & Acrylic Badges | ONPRINT',
    twitter_description: 'Professional magnetic metal and acrylic name badges printed in Dubai.',
    twitter_image: `${SITE_URL}/uploads/categories/name-badges-printing-dubai.jpg`,
    schema_type: 'CollectionPage',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'CollectionPage',
      name: 'Name Badges Printing Dubai',
      url: `${SITE_URL}/categories/name-badges-printing-dubai`,
    }),
    seo_score: 93,
    readability_score: 84,
  },

  // ==========================================
  // 3. SERVICE PAGES (Independent SEO per Service)
  // ==========================================
  {
    page_type: 'service',
    page_id: 1,
    url: '/services/brochures-printing',
    slug: 'brochures-printing',
    meta_title: 'Brochure Printing Services in Dubai | ONPRINT',
    meta_description: 'Professional corporate brochure printing in Dubai. Bi-fold, tri-fold, and multi-page marketing brochures with fast UAE delivery.',
    focus_keyword: 'brochure printing services dubai',
    secondary_keywords: 'corporate brochure printing uae, bi fold brochure dubai, multi page booklet printing',
    h1: 'Commercial Brochure Printing Services in Dubai',
    seo_content: 'Expert multi-page catalog and brochure printing service in Dubai with custom die-cutting, soft-touch matte lamination, and metallic foil finishes.',
    canonical_url: `${SITE_URL}/services/brochures-printing`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Brochure Printing Services in Dubai | ONPRINT',
    og_description: 'High-definition commercial brochure printing services in Dubai.',
    og_image: `${SITE_URL}/uploads/categories/brochures-printing.jpg`,
    twitter_title: 'Brochure Printing Services in Dubai | ONPRINT',
    twitter_description: 'High-definition commercial brochure printing services in Dubai.',
    twitter_image: `${SITE_URL}/uploads/categories/brochures-printing.jpg`,
    schema_type: 'Service',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'Service',
      name: 'Brochure Printing Services Dubai',
      serviceType: 'Commercial Printing',
      provider: { '@id': `${SITE_URL}/#organization` },
      areaServed: { '@type': 'Country', name: 'United Arab Emirates' },
    }),
    seo_score: 95,
    readability_score: 83,
  },
  {
    page_type: 'service',
    page_id: 2,
    url: '/services/business-cards-printing',
    slug: 'business-cards-printing',
    meta_title: 'Business Card Printing in Dubai | ONPRINT',
    meta_description: 'Executive business card printing in Dubai. 350gsm-600gsm cotton card stocks, soft-touch matte lamination, gold foil, and spot UV.',
    focus_keyword: 'business card printing service dubai',
    secondary_keywords: 'executive business cards dubai, cotton visiting cards uae, embossed cards dubai',
    h1: 'Executive Business Card Printing Services in Dubai',
    seo_content: 'Specialized luxury visiting card printing service in Dubai featuring custom hot foil stamping, debossing, colored edges, and ultra-thick duplexed stocks.',
    canonical_url: `${SITE_URL}/services/business-cards-printing`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Business Card Printing in Dubai | ONPRINT',
    og_description: 'Executive business card printing service in Dubai with luxury finishes.',
    og_image: `${SITE_URL}/uploads/categories/business-cards-printing.jpg`,
    twitter_title: 'Business Card Printing in Dubai | ONPRINT',
    twitter_description: 'Executive business card printing service in Dubai with luxury finishes.',
    twitter_image: `${SITE_URL}/uploads/categories/business-cards-printing.jpg`,
    schema_type: 'Service',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'Service',
      name: 'Business Card Printing Services Dubai',
      serviceType: 'Commercial Printing',
      provider: { '@id': `${SITE_URL}/#organization` },
    }),
    seo_score: 96,
    readability_score: 84,
  },
  {
    page_type: 'service',
    page_id: 3,
    url: '/services/flyers-printing-in-dubai',
    slug: 'flyers-printing-in-dubai',
    meta_title: 'Flyer Printing Services in Dubai | Same Day Turnaround | ONPRINT',
    meta_description: 'Order custom marketing flyers in Dubai. Single and double-sided promotional flyers on premium gloss/matte art paper with express delivery.',
    focus_keyword: 'flyer printing service dubai',
    secondary_keywords: 'marketing leaflet printing uae, promotional flyers dubai, same day flyer print',
    h1: 'Express Commercial Flyer Printing Services in Dubai',
    seo_content: 'Fast turnaround commercial marketing flyer printing in Dubai. Precision CMYK offset and digital printing for events, promotions, and corporate campaigns.',
    canonical_url: `${SITE_URL}/services/flyers-printing-in-dubai`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Flyer Printing Services in Dubai | ONPRINT',
    og_description: 'Express promotional flyer printing services across Dubai and UAE.',
    og_image: `${SITE_URL}/uploads/categories/flyers-printing-in-dubai.jpg`,
    twitter_title: 'Flyer Printing Services in Dubai | ONPRINT',
    twitter_description: 'Express promotional flyer printing services across Dubai and UAE.',
    twitter_image: `${SITE_URL}/uploads/categories/flyers-printing-in-dubai.jpg`,
    schema_type: 'Service',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'Service',
      name: 'Flyer Printing Services Dubai',
      serviceType: 'Commercial Printing',
      provider: { '@id': `${SITE_URL}/#organization` },
    }),
    seo_score: 94,
    readability_score: 83,
  },
  {
    page_type: 'service',
    page_id: 4,
    url: '/services/id-card-printing-dubai',
    slug: 'id-card-printing-dubai',
    meta_title: 'Corporate PVC ID Card Printing Dubai | Smart NFC Badges | ONPRINT',
    meta_description: 'High-security corporate PVC ID card printing in Dubai. Crisp photo resolution, smart NFC chips, barcodes, and accessories.',
    focus_keyword: 'pvc id card printing service dubai',
    secondary_keywords: 'corporate employee badges dubai, student id printing uae, smart id card solutions',
    h1: 'Corporate PVC Identity Card Printing Services Dubai',
    seo_content: 'Turnkey employee identification card printing solutions for Dubai businesses, featuring contactless smart chips, barcode encryption, and custom badge accessories.',
    canonical_url: `${SITE_URL}/services/id-card-printing-dubai`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Corporate PVC ID Card Printing Dubai | ONPRINT',
    og_description: 'Secure corporate PVC ID card printing services in Dubai.',
    og_image: `${SITE_URL}/uploads/categories/id-card-printing-dubai.jpg`,
    twitter_title: 'Corporate PVC ID Card Printing Dubai | ONPRINT',
    twitter_description: 'Secure corporate PVC ID card printing services in Dubai.',
    twitter_image: `${SITE_URL}/uploads/categories/id-card-printing-dubai.jpg`,
    schema_type: 'Service',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'Service',
      name: 'PVC ID Card Printing Services Dubai',
      serviceType: 'Identity Printing',
      provider: { '@id': `${SITE_URL}/#organization` },
    }),
    seo_score: 93,
    readability_score: 85,
  },
  {
    page_type: 'service',
    page_id: 5,
    url: '/services/lanyard-printing-dubai',
    slug: 'lanyard-printing-dubai',
    meta_title: 'Custom Branded Lanyard Printing Dubai | Event Neck Straps | ONPRINT',
    meta_description: 'Custom branded neck lanyard printing in Dubai. High-density polyester and satin lanyards with safety buckles and swivel hooks.',
    focus_keyword: 'custom lanyard printing service dubai',
    secondary_keywords: 'branded neck strap printing uae, exhibition lanyards dubai, satin lanyards uae',
    h1: 'Custom Branded Neck Lanyard Printing Services Dubai',
    seo_content: 'Premium screen printed and dye-sublimated neck lanyards for corporate staff, trade shows, and international conferences in Dubai.',
    canonical_url: `${SITE_URL}/services/lanyard-printing-dubai`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Custom Branded Lanyard Printing Dubai | ONPRINT',
    og_description: 'Custom branded event and corporate neck lanyards in Dubai.',
    og_image: `${SITE_URL}/uploads/categories/lanyard-printing-dubai.jpg`,
    twitter_title: 'Custom Branded Lanyard Printing Dubai | ONPRINT',
    twitter_description: 'Custom branded event and corporate neck lanyards in Dubai.',
    twitter_image: `${SITE_URL}/uploads/categories/lanyard-printing-dubai.jpg`,
    schema_type: 'Service',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'Service',
      name: 'Lanyard Printing Services Dubai',
      serviceType: 'Corporate Accessories',
      provider: { '@id': `${SITE_URL}/#organization` },
    }),
    seo_score: 93,
    readability_score: 84,
  },
  {
    page_type: 'service',
    page_id: 6,
    url: '/services/letterheads-printing-dubai',
    slug: 'letterheads-printing-dubai',
    meta_title: 'Executive Corporate Letterhead Printing Dubai | ONPRINT',
    meta_description: 'Executive corporate letterhead printing in Dubai. 120gsm smooth laser-guaranteed paper for official contracts and proposals.',
    focus_keyword: 'letterhead printing service dubai',
    secondary_keywords: 'corporate stationery printing dubai, official letterhead paper uae, 120gsm letterheads',
    h1: 'Executive Corporate Letterhead Printing Services Dubai',
    seo_content: 'Official corporate stationery printing on 120gsm smooth laser-guaranteed stock, engineered for executive contracts, proposals, and official correspondence in Dubai.',
    canonical_url: `${SITE_URL}/services/letterheads-printing-dubai`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Executive Corporate Letterhead Printing Dubai | ONPRINT',
    og_description: 'Executive corporate letterheads printed on 120gsm laser-guaranteed stock.',
    og_image: `${SITE_URL}/uploads/categories/letterheads-printing-dubai.jpg`,
    twitter_title: 'Executive Corporate Letterhead Printing Dubai | ONPRINT',
    twitter_description: 'Executive corporate letterheads printed on 120gsm laser-guaranteed stock.',
    twitter_image: `${SITE_URL}/uploads/categories/letterheads-printing-dubai.jpg`,
    schema_type: 'Service',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'Service',
      name: 'Letterhead Printing Services Dubai',
      serviceType: 'Stationery Printing',
      provider: { '@id': `${SITE_URL}/#organization` },
    }),
    seo_score: 92,
    readability_score: 87,
  },
  {
    page_type: 'service',
    page_id: 7,
    url: '/services/name-badges-printing-dubai',
    slug: 'name-badges-printing-dubai',
    meta_title: 'Magnetic Metal & Acrylic Name Badges Printing Dubai | ONPRINT',
    meta_description: 'Professional staff name badges printing in Dubai. Brushed silver, gold, and acrylic magnetic badges with domed epoxy resin.',
    focus_keyword: 'name badge printing service dubai',
    secondary_keywords: 'magnetic staff badges dubai, acrylic name tags uae, corporate employee badges',
    h1: 'Professional Magnetic Name Badges Printing Services Dubai',
    seo_content: 'Laser-cut brushed champagne gold, silver, and crystal-clear acrylic staff name badges with protective domed resin and garment-safe magnetic clips.',
    canonical_url: `${SITE_URL}/services/name-badges-printing-dubai`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Magnetic Metal & Acrylic Name Badges Printing Dubai | ONPRINT',
    og_description: 'Professional magnetic metal and acrylic name badges printed in Dubai.',
    og_image: `${SITE_URL}/uploads/categories/name-badges-printing-dubai.jpg`,
    twitter_title: 'Magnetic Metal & Acrylic Name Badges Printing Dubai | ONPRINT',
    twitter_description: 'Professional magnetic metal and acrylic name badges printed in Dubai.',
    twitter_image: `${SITE_URL}/uploads/categories/name-badges-printing-dubai.jpg`,
    schema_type: 'Service',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'Service',
      name: 'Name Badge Printing Services Dubai',
      serviceType: 'Corporate Accessories',
      provider: { '@id': `${SITE_URL}/#organization` },
    }),
    seo_score: 93,
    readability_score: 85,
  },

  // ==========================================
  // 4. PRODUCT PAGES (Independent SEO per Product)
  // ==========================================
  {
    page_type: 'product',
    page_id: 1,
    url: '/products/luxury-velvet-business-cards',
    slug: 'luxury-velvet-business-cards',
    meta_title: 'Luxury Velvet Business Cards Dubai | Gold Foil Stamping | ONPRINT',
    meta_description: 'Executive 450gsm velvet business cards with gold foil stamping & painted edges in Dubai. Order bespoke luxury cards with express delivery.',
    focus_keyword: 'luxury velvet business cards dubai',
    secondary_keywords: 'gold foil business cards dubai, 450gsm visiting cards uae, soft touch business cards',
    h1: 'Executive Luxury Velvet Business Cards Dubai',
    seo_content: 'Order executive 450gsm velvet soft-touch business cards with metallic gold foil stamping and painted edges in Dubai.',
    canonical_url: `${SITE_URL}/products/luxury-velvet-business-cards`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Luxury Velvet Business Cards Dubai | Gold Foil Stamping | ONPRINT',
    og_description: 'Executive 450gsm velvet business cards with metallic gold foil stamping in Dubai.',
    og_image: `${SITE_URL}/uploads/categories/business-cards-printing.jpg`,
    twitter_title: 'Luxury Velvet Business Cards Dubai | Gold Foil Stamping | ONPRINT',
    twitter_description: 'Executive 450gsm velvet business cards with metallic gold foil stamping in Dubai.',
    twitter_image: `${SITE_URL}/uploads/categories/business-cards-printing.jpg`,
    schema_type: 'Product',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'Product',
      name: 'Luxury Velvet Business Cards',
      description: 'Executive 450gsm silk cards with soft-touch matte velvet lamination and metallic gold foil stamping.',
      sku: 'ONP-PROD-BC-001',
      brand: { '@type': 'Brand', name: 'ONPRINT' },
      offers: {
        '@type': 'Offer',
        price: '150.00',
        priceCurrency: 'AED',
        availability: 'https://schema.org/InStock',
        url: `${SITE_URL}/products/luxury-velvet-business-cards`,
      },
    }),
    seo_score: 95,
    readability_score: 84,
  },
  {
    page_type: 'product',
    page_id: 2,
    url: '/products/corporate-bi-fold-brochures',
    slug: 'corporate-bi-fold-brochures',
    meta_title: 'Corporate Bi-Fold Brochures Dubai | Custom Art Paper | ONPRINT',
    meta_description: 'Commercial bi-fold brochure printing in Dubai. 250gsm premium art paper, vibrant CMYK color calibration, and express turnaround across UAE.',
    focus_keyword: 'corporate bi-fold brochures dubai',
    secondary_keywords: 'bifold brochure printing dubai, commercial marketing brochures uae, 250gsm folded leaflets',
    h1: 'Corporate Bi-Fold Brochure Printing Dubai',
    seo_content: 'High-definition 4-page bi-fold corporate brochures on 250gsm coated art paper with protective matte or gloss coating.',
    canonical_url: `${SITE_URL}/products/corporate-bi-fold-brochures`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Corporate Bi-Fold Brochures Dubai | Custom Art Paper | ONPRINT',
    og_description: 'Commercial bi-fold brochures on 250gsm art paper printed in Dubai.',
    og_image: `${SITE_URL}/uploads/categories/brochures-printing.jpg`,
    twitter_title: 'Corporate Bi-Fold Brochures Dubai | Custom Art Paper | ONPRINT',
    twitter_description: 'Commercial bi-fold brochures on 250gsm art paper printed in Dubai.',
    twitter_image: `${SITE_URL}/uploads/categories/brochures-printing.jpg`,
    schema_type: 'Product',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'Product',
      name: 'Corporate Bi-Fold Brochures',
      description: 'High-definition 4-page bi-fold corporate brochures on 250gsm coated art paper.',
      sku: 'ONP-PROD-BR-002',
      brand: { '@type': 'Brand', name: 'ONPRINT' },
      offers: {
        '@type': 'Offer',
        price: '350.00',
        priceCurrency: 'AED',
        availability: 'https://schema.org/InStock',
        url: `${SITE_URL}/products/corporate-bi-fold-brochures`,
      },
    }),
    seo_score: 94,
    readability_score: 82,
  },
  {
    page_type: 'product',
    page_id: 3,
    url: '/products/high-impact-gloss-marketing-flyers',
    slug: 'high-impact-gloss-marketing-flyers',
    meta_title: 'High-Impact Marketing Flyers Dubai | Express CMYK Print | ONPRINT',
    meta_description: 'Order commercial gloss marketing flyers in Dubai. Double-sided high-resolution printing on 170gsm art paper with same-day delivery.',
    focus_keyword: 'gloss marketing flyers dubai',
    secondary_keywords: 'promotional flyer printing dubai, double sided flyers uae, 170gsm marketing leaflets',
    h1: 'High-Impact Commercial Marketing Flyers Dubai',
    seo_content: 'Double-sided commercial promotional flyers printed on 170gsm gloss art paper with vibrant CMYK ink fidelity.',
    canonical_url: `${SITE_URL}/products/high-impact-gloss-marketing-flyers`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'High-Impact Marketing Flyers Dubai | Express CMYK Print | ONPRINT',
    og_description: 'Commercial gloss flyers on 170gsm art paper printed with same-day turnaround in Dubai.',
    og_image: `${SITE_URL}/uploads/categories/flyers-printing-in-dubai.jpg`,
    twitter_title: 'High-Impact Marketing Flyers Dubai | Express CMYK Print | ONPRINT',
    twitter_description: 'Commercial gloss flyers on 170gsm art paper printed with same-day turnaround in Dubai.',
    twitter_image: `${SITE_URL}/uploads/categories/flyers-printing-in-dubai.jpg`,
    schema_type: 'Product',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'Product',
      name: 'High-Impact Gloss Marketing Flyers',
      description: 'Double-sided commercial promotional flyers printed on 170gsm gloss art paper.',
      sku: 'ONP-PROD-FL-003',
      brand: { '@type': 'Brand', name: 'ONPRINT' },
      offers: {
        '@type': 'Offer',
        price: '120.00',
        priceCurrency: 'AED',
        availability: 'https://schema.org/InStock',
        url: `${SITE_URL}/products/high-impact-gloss-marketing-flyers`,
      },
    }),
    seo_score: 94,
    readability_score: 83,
  },
  {
    page_type: 'product',
    page_id: 4,
    url: '/products/secure-smart-nfc-pvc-id-cards',
    slug: 'secure-smart-nfc-pvc-id-cards',
    meta_title: 'Secure Smart NFC PVC ID Cards Dubai | RFID Badges | ONPRINT',
    meta_description: 'High-security corporate PVC ID cards with NFC & RFID chips in Dubai. High-resolution photo printing, barcodes, and custom security overlays.',
    focus_keyword: 'smart nfc pvc id cards dubai',
    secondary_keywords: 'rfid id badges dubai, corporate employee cards uae, pvc access cards dubai',
    h1: 'Secure Smart NFC PVC ID Cards Dubai',
    seo_content: 'CR80 standard PVC identity cards with embedded NFC/RFID chips, high-definition photo print and security overlay.',
    canonical_url: `${SITE_URL}/products/secure-smart-nfc-pvc-id-cards`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Secure Smart NFC PVC ID Cards Dubai | RFID Badges | ONPRINT',
    og_description: 'High-security corporate PVC ID cards with NFC & RFID chips in Dubai.',
    og_image: `${SITE_URL}/uploads/categories/id-card-printing-dubai.jpg`,
    twitter_title: 'Secure Smart NFC PVC ID Cards Dubai | RFID Badges | ONPRINT',
    twitter_description: 'High-security corporate PVC ID cards with NFC & RFID chips in Dubai.',
    twitter_image: `${SITE_URL}/uploads/categories/id-card-printing-dubai.jpg`,
    schema_type: 'Product',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'Product',
      name: 'Secure Smart NFC PVC ID Cards',
      description: 'CR80 standard PVC identity cards with embedded NFC/RFID chips and photo print.',
      sku: 'ONP-PROD-ID-004',
      brand: { '@type': 'Brand', name: 'ONPRINT' },
      offers: {
        '@type': 'Offer',
        price: '25.00',
        priceCurrency: 'AED',
        availability: 'https://schema.org/InStock',
        url: `${SITE_URL}/products/secure-smart-nfc-pvc-id-cards`,
      },
    }),
    seo_score: 93,
    readability_score: 84,
  },
  {
    page_type: 'product',
    page_id: 5,
    url: '/products/custom-branded-satin-neck-lanyards',
    slug: 'custom-branded-satin-neck-lanyards',
    meta_title: 'Custom Satin Neck Lanyards Dubai | Safety Breakaway Clips | ONPRINT',
    meta_description: 'Custom branded neck lanyards in Dubai. Silky satin polyester, full color logo printing, safety release buckles, and metal swivel clips.',
    focus_keyword: 'satin neck lanyards dubai',
    secondary_keywords: 'custom printed lanyards dubai, branded neck straps uae, event lanyards dubai',
    h1: 'Custom Branded Satin Neck Lanyards Dubai',
    seo_content: 'Silky 20mm premium neck lanyards featuring silk-screen company branding, safety breakaway buckle and swivel hook.',
    canonical_url: `${SITE_URL}/products/custom-branded-satin-neck-lanyards`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Custom Satin Neck Lanyards Dubai | Safety Breakaway Clips | ONPRINT',
    og_description: 'Custom branded satin neck lanyards with safety buckles in Dubai.',
    og_image: `${SITE_URL}/uploads/categories/lanyard-printing-dubai.jpg`,
    twitter_title: 'Custom Satin Neck Lanyards Dubai | Safety Breakaway Clips | ONPRINT',
    twitter_description: 'Custom branded satin neck lanyards with safety buckles in Dubai.',
    twitter_image: `${SITE_URL}/uploads/categories/lanyard-printing-dubai.jpg`,
    schema_type: 'Product',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'Product',
      name: 'Custom Branded Satin Neck Lanyards',
      description: 'Silky 20mm premium neck lanyards featuring silk-screen branding.',
      sku: 'ONP-PROD-LN-005',
      brand: { '@type': 'Brand', name: 'ONPRINT' },
      offers: {
        '@type': 'Offer',
        price: '8.50',
        priceCurrency: 'AED',
        availability: 'https://schema.org/InStock',
        url: `${SITE_URL}/products/custom-branded-satin-neck-lanyards`,
      },
    }),
    seo_score: 93,
    readability_score: 85,
  },
  {
    page_type: 'product',
    page_id: 6,
    url: '/products/executive-stationery-letterheads',
    slug: 'executive-stationery-letterheads',
    meta_title: 'Executive Uncoated Letterheads Dubai | 120gsm Laser Guaranteed | ONPRINT',
    meta_description: 'Corporate letterhead printing in Dubai. 120gsm ultra-smooth laser-compatible paper with crisp Pantone color fidelity for official business stationery.',
    focus_keyword: 'executive stationery letterheads dubai',
    secondary_keywords: '120gsm letterhead paper dubai, official corporate stationery uae, laser guaranteed letterheads',
    h1: 'Executive Uncoated Corporate Letterheads Dubai',
    seo_content: '120gsm ultra-smooth laser-compatible corporate letterheads with Pantone precision color matching.',
    canonical_url: `${SITE_URL}/products/executive-stationery-letterheads`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Executive Uncoated Letterheads Dubai | 120gsm Laser Guaranteed | ONPRINT',
    og_description: 'Corporate letterheads printed on 120gsm laser-guaranteed paper in Dubai.',
    og_image: `${SITE_URL}/uploads/categories/letterheads-printing-dubai.jpg`,
    twitter_title: 'Executive Uncoated Letterheads Dubai | 120gsm Laser Guaranteed | ONPRINT',
    twitter_description: 'Corporate letterheads printed on 120gsm laser-guaranteed paper in Dubai.',
    twitter_image: `${SITE_URL}/uploads/categories/letterheads-printing-dubai.jpg`,
    schema_type: 'Product',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'Product',
      name: 'Executive Stationery Letterheads',
      description: '120gsm ultra-smooth laser-compatible corporate letterheads.',
      sku: 'ONP-PROD-LH-006',
      brand: { '@type': 'Brand', name: 'ONPRINT' },
      offers: {
        '@type': 'Offer',
        price: '180.00',
        priceCurrency: 'AED',
        availability: 'https://schema.org/InStock',
        url: `${SITE_URL}/products/executive-stationery-letterheads`,
      },
    }),
    seo_score: 92,
    readability_score: 86,
  },
  {
    page_type: 'product',
    page_id: 7,
    url: '/products/magnetic-brushed-metal-name-badges',
    slug: 'magnetic-brushed-metal-name-badges',
    meta_title: 'Magnetic Domed Name Badges Dubai | Brushed Silver & Gold | ONPRINT',
    meta_description: 'Order magnetic staff name badges in Dubai. Brushed metal and acrylic finishes with protective domed resin and strong magnetic fasteners.',
    focus_keyword: 'magnetic metal name badges dubai',
    secondary_keywords: 'brushed gold staff badges dubai, domed name tags uae, executive name badges dubai',
    h1: 'Magnetic Brushed Metal Name Badges Dubai',
    seo_content: 'Laser-engraved brushed champagne gold and silver staff name badges with strong neodymium magnet fastener.',
    canonical_url: `${SITE_URL}/products/magnetic-brushed-metal-name-badges`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Magnetic Domed Name Badges Dubai | Brushed Silver & Gold | ONPRINT',
    og_description: 'Laser-engraved brushed metal staff name badges with strong magnetic fastener in Dubai.',
    og_image: `${SITE_URL}/uploads/categories/name-badges-printing-dubai.jpg`,
    twitter_title: 'Magnetic Domed Name Badges Dubai | Brushed Silver & Gold | ONPRINT',
    twitter_description: 'Laser-engraved brushed metal staff name badges with strong magnetic fastener in Dubai.',
    twitter_image: `${SITE_URL}/uploads/categories/name-badges-printing-dubai.jpg`,
    schema_type: 'Product',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'Product',
      name: 'Magnetic Brushed Metal Name Badges',
      description: 'Laser-engraved brushed champagne gold and silver staff name badges.',
      sku: 'ONP-PROD-NB-007',
      brand: { '@type': 'Brand', name: 'ONPRINT' },
      offers: {
        '@type': 'Offer',
        price: '35.00',
        priceCurrency: 'AED',
        availability: 'https://schema.org/InStock',
        url: `${SITE_URL}/products/magnetic-brushed-metal-name-badges`,
      },
    }),
    seo_score: 93,
    readability_score: 85,
  },

  // ==========================================
  // 5. BLOG ARTICLES (Independent SEO per Article)
  // ==========================================
  {
    page_type: 'blog',
    page_id: 1,
    url: '/blog/printing-services-dubai',
    slug: 'printing-services-dubai',
    meta_title: 'The Complete Guide to Commercial & Digital Printing in Dubai | ONPRINT',
    meta_description: 'Everything UAE businesses need to know about commercial, digital, and offset printing in Dubai. Paper stocks, prepress specs, turnaround, and finishing options.',
    focus_keyword: 'commercial printing guide dubai',
    secondary_keywords: 'digital printing guide uae, offset printing dubai specs, commercial print press al quoz',
    h1: 'The Complete Guide to Commercial & Digital Printing Services in Dubai',
    seo_content: 'Comprehensive technical overview of commercial print technologies, digital vs offset selection criteria, and prepress best practices for Dubai businesses.',
    canonical_url: `${SITE_URL}/blog/printing-services-dubai`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'The Complete Guide to Commercial & Digital Printing in Dubai | ONPRINT',
    og_description: 'Authoritative guide to commercial and digital printing services in Dubai.',
    og_image: `${SITE_URL}/logo_icon.png`,
    twitter_title: 'The Complete Guide to Commercial & Digital Printing in Dubai | ONPRINT',
    twitter_description: 'Authoritative guide to commercial and digital printing services in Dubai.',
    twitter_image: `${SITE_URL}/logo_icon.png`,
    schema_type: 'BlogPosting',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'BlogPosting',
      headline: 'The Complete Guide to Commercial & Digital Printing Services in Dubai',
      url: `${SITE_URL}/blog/printing-services-dubai`,
      author: { '@type': 'Organization', name: 'ONPRINT Editorial Team' },
      publisher: { '@id': `${SITE_URL}/#organization` },
    }),
    seo_score: 96,
    readability_score: 87,
  },
  {
    page_type: 'blog',
    page_id: 2,
    url: '/blog/corporate-gifts-dubai',
    slug: 'corporate-gifts-dubai',
    meta_title: 'Top Corporate Gift & Promotional Merchandise Ideas in Dubai | ONPRINT',
    meta_description: 'Discover luxury corporate gift trends and branded promotional merchandise in Dubai for exhibitions, VIP client appreciation, and corporate events.',
    focus_keyword: 'corporate gifts ideas dubai',
    secondary_keywords: 'promotional merchandise dubai, luxury executive gifts uae, branded swag boxes dubai',
    h1: 'Top Corporate Gift & Promotional Merchandise Ideas for Dubai Businesses',
    seo_content: 'Curated editorial review of top executive gift ideas, custom packaging presentations, and branded merchandise for UAE enterprises.',
    canonical_url: `${SITE_URL}/blog/corporate-gifts-dubai`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Top Corporate Gift & Promotional Merchandise Ideas in Dubai | ONPRINT',
    og_description: 'Executive merchandise and VIP gift box inspiration for Dubai enterprises.',
    og_image: `${SITE_URL}/logo_icon.png`,
    twitter_title: 'Top Corporate Gift & Promotional Merchandise Ideas in Dubai | ONPRINT',
    twitter_description: 'Executive merchandise and VIP gift box inspiration for Dubai enterprises.',
    twitter_image: `${SITE_URL}/logo_icon.png`,
    schema_type: 'BlogPosting',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'BlogPosting',
      headline: 'Top Corporate Gift & Promotional Merchandise Ideas for Dubai Businesses',
      url: `${SITE_URL}/blog/corporate-gifts-dubai`,
      author: { '@type': 'Organization', name: 'ONPRINT Editorial Team' },
      publisher: { '@id': `${SITE_URL}/#organization` },
    }),
    seo_score: 95,
    readability_score: 88,
  },
  {
    page_type: 'blog',
    page_id: 3,
    url: '/blog/business-card-design-printing',
    slug: 'business-card-design-printing',
    meta_title: 'Luxury Business Card Printing in Dubai: Stocks & Finishes Guide | ONPRINT',
    meta_description: 'Learn how to choose the right paper GSM, velvet lamination, metallic foil, and embossing for luxury business cards in Dubai.',
    focus_keyword: 'luxury business card stocks dubai',
    secondary_keywords: 'visiting card finishes uae, gold foil business cards guide, 600gsm cotton cards dubai',
    h1: 'Luxury Business Card Printing in Dubai: Paper Stocks, Finishes & Specs',
    seo_content: 'Technical analysis of tactile finishes, cotton vs silk card stocks, hot foil stamping dies, and edge painting techniques for executive cards.',
    canonical_url: `${SITE_URL}/blog/business-card-design-printing`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'Luxury Business Card Printing in Dubai: Stocks & Finishes Guide | ONPRINT',
    og_description: 'Technical paper stock and luxury finish guide for executive business cards in Dubai.',
    og_image: `${SITE_URL}/logo_icon.png`,
    twitter_title: 'Luxury Business Card Printing in Dubai: Stocks & Finishes Guide | ONPRINT',
    twitter_description: 'Technical paper stock and luxury finish guide for executive business cards in Dubai.',
    twitter_image: `${SITE_URL}/logo_icon.png`,
    schema_type: 'BlogPosting',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'BlogPosting',
      headline: 'Luxury Business Card Printing in Dubai: Paper Stocks, Finishes & Specs',
      url: `${SITE_URL}/blog/business-card-design-printing`,
      author: { '@type': 'Organization', name: 'ONPRINT Editorial Team' },
      publisher: { '@id': `${SITE_URL}/#organization` },
    }),
    seo_score: 95,
    readability_score: 86,
  },
  {
    page_type: 'blog',
    page_id: 4,
    url: '/blog/choosing-printing-company-dubai',
    slug: 'choosing-printing-company-dubai',
    meta_title: 'How to Choose the Best Commercial Printing Company in Dubai | ONPRINT',
    meta_description: 'Key criteria for selecting a commercial printing press in Dubai. Color proofing standards, machinery capabilities, turnaround reliability, and pricing transparency.',
    focus_keyword: 'choose printing company dubai',
    secondary_keywords: 'commercial printer evaluation uae, best printing press al quoz, print vendor checklist dubai',
    h1: 'How to Choose the Best Commercial Printing Company in Dubai, UAE',
    seo_content: 'Corporate procurement checklist for assessing print presses in the UAE, including machinery calibration, paper certifications, and contract SLA terms.',
    canonical_url: `${SITE_URL}/blog/choosing-printing-company-dubai`,
    robots_index: 'index',
    robots_follow: 'follow',
    og_title: 'How to Choose the Best Commercial Printing Company in Dubai | ONPRINT',
    og_description: 'Corporate checklist for selecting premier printing presses in Dubai.',
    og_image: `${SITE_URL}/logo_icon.png`,
    twitter_title: 'How to Choose the Best Commercial Printing Company in Dubai | ONPRINT',
    twitter_description: 'Corporate checklist for selecting premier printing presses in Dubai.',
    twitter_image: `${SITE_URL}/logo_icon.png`,
    schema_type: 'BlogPosting',
    schema_markup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'BlogPosting',
      headline: 'How to Choose the Best Commercial Printing Company in Dubai, UAE',
      url: `${SITE_URL}/blog/choosing-printing-company-dubai`,
      author: { '@type': 'Organization', name: 'ONPRINT Editorial Team' },
      publisher: { '@id': `${SITE_URL}/#organization` },
    }),
    seo_score: 94,
    readability_score: 87,
  },
]

module.exports = {
  initialPageSeoRecords,
  SITE_URL,
}
