import Container from '../../components/Container'
import Breadcrumbs from '../../components/Breadcrumbs'
import SEOHead from '../../components/SEOHead'

const termsSections = [
  {
    title: '1. Agreement & Acceptance of Terms',
    body: 'These Terms & Conditions ("Terms", "Agreement") constitute a legally binding agreement between ONPRINT Printing & Branding Solutions LLC ("ONPRINT", "we", "us", or "our"), operating in Al Quoz, Dubai, UAE, and any client, individual, or corporate entity ("Client", "Customer", "you") ordering custom printing, luxury packaging, promotional products, graphic preparation, or associated commercial finishing services. By requesting a quotation, approving a digital proof, submitting production files, or completing an invoice payment, you acknowledge that you have read, understood, and agreed to be bound by these Terms.',
  },
  {
    title: '2. Quotations, Pricing & Validity',
    body: 'Official quotations generated by ONPRINT via our website, email, or WhatsApp concierge are valid for thirty (30) calendar days from the issuance date, unless specifically stated otherwise. All prices are quoted in United Arab Emirates Dirhams (AED) and are subject to the standard 5% UAE Value Added Tax (VAT) in accordance with Federal Tax Authority regulations. Final pricing is confirmed once exact technical specifications (paper stock weight, custom dimensions, die-line complexity, foil stamping dies, spot UV areas, and quantity tiers) are verified by our pre-press technical department.',
  },
  {
    title: '3. Pre-Press Proofing & Digital Approval',
    body: 'Commercial production begins strictly after the Client provides explicit written approval (via email, portal confirmation, or digital sign-off) of the final PDF production proof. The Client is solely responsible for verifying all design elements, text copy, spelling, grammar, telephone numbers, QR code destinations, barcode readability, layout orientation, and bleed dimensions on the approved proof. ONPRINT accepts no financial or production liability for errors, omissions, or misspellings present in customer-approved proof files.',
  },
  {
    title: '4. Artwork Guidelines, File Formats & Color Accuracy',
    body: 'Clients must supply print-ready artwork formatted in CMYK color mode with high resolution (minimum 300 DPI at 100% scale), converted vector fonts/outlines, and a minimum of 3mm bleed on all trimmed edges. While ONPRINT utilizes advanced spectrophotometer-calibrated Heidelberg offset presses and digital production engines adhering to ISO 12647 color standards, slight color variations inherent in different substrate stocks (such as coated art cards versus textured uncoated linen or kraft boards) and computer screen RGB-to-CMYK conversions are standard commercial tolerances and do not constitute defective manufacturing.',
  },
  {
    title: '5. Production Turnaround Times & Delivery',
    body: 'Estimated production lead times (Standard 2–4 business days, Express 24-hour, or Same-Day Priority) commence strictly from the moment both payment confirmation and written proof approval have been received. While we maintain a 99.4% on-time dispatch record across Dubai, Abu Dhabi, Sharjah, Ajman, and the wider UAE, ONPRINT is not liable for indirect transit delays resulting from third-party courier handling, customs clearance for international consignments, severe weather conditions, or force majeure events outside our reasonable control.',
  },
  {
    title: '6. Payment Terms & Ownership of Goods',
    body: 'Unless a formal commercial credit facility has been approved in writing by ONPRINT management, full payment or a minimum 50% production advance is required prior to job initiation, with the remaining balance due upon job completion prior to dispatch. Title and ownership of custom-manufactured print goods remain with ONPRINT until full invoice settlement has been completed.',
  },
  {
    title: '7. Cancellations, Modifications & Reprint Policies',
    body: 'Because all custom-printed goods, tailored packaging boxes, and branded merchandise are manufactured to bespoke client specifications, orders cannot be cancelled or returned for refund once printing plates have been produced or physical substrate cutting has commenced. In the rare event of a verified manufacturing defect or significant deviation from the approved digital proof, the Client must notify ONPRINT in writing within forty-eight (48) hours of delivery with photographic evidence; upon verification, ONPRINT will promptly re-manufacture and replace the defective quantity at no additional charge.',
  },
  {
    title: '8. Intellectual Property & Indemnification',
    body: 'The Client warrants that they own or hold all required legal rights, copyright licenses, and trademark permissions for all logos, artwork, images, and text submitted for reproduction. The Client agrees to indemnify, defend, and hold harmless ONPRINT and its officers, directors, and employees against any third-party claims, liabilities, legal fees, or damages arising from alleged copyright, trademark, or intellectual property infringement associated with Client-supplied materials.',
  },
  {
    title: '9. Limitation of Liability',
    body: 'To the maximum extent permitted under UAE commercial law, ONPRINT\'s total aggregate liability for any claim, defect, breach of contract, or delayed delivery shall be strictly limited to the total monetary amount paid by the Client for the specific affected order. In no event shall ONPRINT be liable for any indirect, special, incidental, punitive, or consequential commercial damages, including loss of business profits, exhibition deadlines, or marketing opportunities.',
  },
  {
    title: '10. Governing Law & Dispute Resolution',
    body: 'These Terms and Conditions shall be governed by, construed, and enforced in accordance with the federal laws of the United Arab Emirates and the local laws of the Emirate of Dubai. Any dispute, controversy, or claim arising out of or relating to commercial transactions with ONPRINT that cannot be resolved amicably shall be submitted to the exclusive jurisdiction of the competent courts of Dubai, United Arab Emirates.',
  },
]

export default function TermsPage() {
  return (
    <div className="py-16 sm:py-24">
      <SEOHead
        title="Terms & Conditions | ONPRINT Dubai — Commercial Printing & Ordering Terms"
        description="Comprehensive Terms & Conditions for commercial printing, packaging production, digital proof approval, and delivery with ONPRINT Dubai, UAE."
        keywords="terms and conditions onprint, commercial printing terms dubai, proof approval policy uae, printing service agreement dubai"
        canonicalPath="/terms"
        breadcrumbs={[{ name: 'Terms & Conditions', url: '/terms' }]}
      />

      <Container className="max-w-4xl">
        <Breadcrumbs items={[{ name: 'Terms & Conditions' }]} />
        <div className="border-b border-border pb-8">
          <p className="text-xs font-black uppercase tracking-[0.25em] text-accent">Commercial Terms</p>
          <h1 className="font-display mt-3 text-3xl font-extrabold tracking-tight text-primary sm:text-5xl">
            Terms &amp; Conditions of Service
          </h1>
          <p className="mt-4 text-sm font-semibold text-secondary">
            Standard Commercial Terms • Effective Date: January 1, 2026 • Al Quoz, Dubai, UAE
          </p>
          <p className="mt-3 text-sm leading-relaxed text-secondary">
            Please read these commercial terms carefully before submitting artwork files, requesting custom quotations, or authorizing print production with ONPRINT Printing &amp; Branding Solutions LLC.
          </p>
        </div>

        <div className="mt-10 divide-y divide-border">
          {termsSections.map((s) => (
            <article key={s.title} className="py-8">
              <h2 className="font-display text-lg sm:text-xl font-bold text-primary">{s.title}</h2>
              <p className="mt-3 text-sm sm:text-base leading-relaxed text-secondary text-justify">{s.body}</p>
            </article>
          ))}
        </div>
      </Container>
    </div>
  )
}
